In [1]:
import logging

# Set the logging level for urllib3 and openai modules
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("openai").setLevel(logging.WARNING)

In [2]:
import os
from bollama import BOAgent, BOTools
os.environ["OPENAI_API_KEY"] = "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"
os.environ["SERPAPI_API_KEY"] = "b2c71087533bf29e801f110250cee763724d68e0f1a5ad49bbdaddac04f11aff"

To use the Graphein submodule graphein.protein.features.sequence.embeddings, you need to install: biovec 
biovec cannot be installed via conda
DEBUG:matplotlib:matplotlib data path: /home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/rankovic/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/rankovic/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/rankovic/.cache/matplotlib/fontlist-v330.json
To do so, use the following command: conda install -c pytorch3d pytorch3d
To do so, use the following command: conda install -c pytorch3d pytorch3d
INFO:rdkit:Enabling RDKit 2022.09.5 jupyter extensions
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/rankovic/projects/BOLLaMa/notebooks, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/rankovic/projects/BOLLaMa/no

In [3]:
carlos_the_frustrated_chemist = BOAgent(
    BOTools().botools,
    model="gpt-3.5-turbo"
)

In [4]:
prompt = (
    "Hello gpt. I want to optimize the additives for a chemical reaction. "
    "Can you please suggest what experiments to do first, "
    "and then let's do multiple optimization steps until I am satisfied."
    "Let's start with 4 experiments."
    
    "Everytime you propose an experiment, ask for my input to know the result of the experiment."
)

carlos_the_frustrated_chemist.run({"input":{"user": prompt}, "chat_history": {}})



> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: Get initial experiments.
Action Input: 4[427] baseline reaction index
[137, 437, 20, 613]  indices before 
[137, 438, 20, 614] indices after
Selected reactions: [137, 438, 20, 614]

Observation: ['CCCC(CO)O', 'c1ccc2c(c1)nnn2C(=N)n3c4ccccc4nn3', 'C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](c3ccnc4c3cccc4)O', 'c1[nH]c2c(n1)c(=O)[nH]c(=O)[nH]2']
Thought:Do I need to use a tool? Yes
Action: Get user input.
Action Input: What was the result of the first experiment?
Observation: 54679.3025, 13518.81469, 39731.89917, 26111.90483
Thought:

/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
ERROR:wandb.jupyter:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


Do I need to use a tool? Yes
Action: Propose next experiment.
Action Input: {'CCCC(CO)O': 54679.3025, 'c1ccc2c(c1)nnn2C(=N)n3c4ccccc4nn3': 13518.81469, 'C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](c3ccnc4c3cccc4)O': 39731.89917, 'c1[nH]c2c(n1)c(=O)[nH]c(=O)[nH]2': 26111.90483}

wandb: Currently logged in as: bojana-rankovic (liac). Use `wandb login --relogin` to force relogin
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/rankovic/projects/BOLLaMa, universal_newlines=False, shell=None, istream=<valid stream>)


INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
INFO:pytorch_lightning.callbacks.model_summary:
  | Name  | Type | Params
-------------------------------
0 | model | GP   | 3     
-------------------------------
3         Trainable

Training: 0it [00:00, ?it/s]

tensor([625]) best idxes
ADDITIVE C(C(CO)CO)O


/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:233: UserWarning: You called `self.log('suggestion_idx', ...)` in your `training_step` but the value needs to be floating point. Converting it to torch.float32.
  warning_cache.warn(


Validation: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=1` reached.



Observation: C(C(CO)CO)O
Thought:Do I need to use a tool? Yes
Action: Get user input.
Action Input: What was the result of the second experiment?
Observation: 60609.38117
Thought:

/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/rankovic/projects/BOLLaMa, universal_newlines=False, shell=None, istream=<valid stream>)


Do I need to use a tool? Yes
Action: Propose next experiment.
Action Input: {'CCCC(CO)O': 54679.3025, 'c1ccc2c(c1)nnn2C(=N)n3c4ccccc4nn3': 13518.81469, 'C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](c3ccnc4c3cccc4)O': 39731.89917, 'c1[nH]c2c(n1)c(=O)[nH]c(=O)[nH]2': 26111.90483, 'C(C(CO)CO)O': 60609.38117}

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
INFO:pytorch_lightning.callbacks.model_summary:
  | Name  | Type | Params
-------------------------------
0 | model | GP   | 3     
-------------------------------
3         Trainable

Training: 0it [00:00, ?it/s]

tensor([91]) best idxes
ADDITIVE CC(C)(CO)CO


/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)


Validation: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=1` reached.



Observation: CC(C)(CO)CO
Thought:Do I need to use a tool? Yes
Action: Get user input.
Action Input: What was the result of the third experiment?
Observation: 64968.11402
Thought:

/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/rankovic/projects/BOLLaMa, universal_newlines=False, shell=None, istream=<valid stream>)


Do I need to use a tool? Yes
Action: Propose next experiment.
Action Input: {'CCCC(CO)O': 54679.3025, 'c1ccc2c(c1)nnn2C(=N)n3c4ccccc4nn3': 13518.81469, 'C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](c3ccnc4c3cccc4)O': 39731.89917, 'c1[nH]c2c(n1)c(=O)[nH]c(=O)[nH]2': 26111.90483, 'C(C(CO)CO)O': 60609.38117, 'CC(C)(CO)CO': 64968.11402}

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
INFO:pytorch_lightning.callbacks.model_summary:
  | Name  | Type | Params
-------------------------------
0 | model | GP   | 3     
-------------------------------
3         Trainable

Training: 0it [00:00, ?it/s]

tensor([94]) best idxes
ADDITIVE CC(C)(CCO)O


/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)


Validation: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=1` reached.



Observation: CC(C)(CCO)O
Thought:Do I need to use a tool? Yes
Action: Get user input.
Action Input: What was the result of the fourth experiment?
Observation: 57565.50571
Thought:

/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/rankovic/projects/BOLLaMa, universal_newlines=False, shell=None, istream=<valid stream>)


Do I need to use a tool? Yes
Action: Propose next experiment.
Action Input: {'CCCC(CO)O': 54679.3025, 'c1ccc2c(c1)nnn2C(=N)n3c4ccccc4nn3': 13518.81469, 'C=C[C@H]1CN2CC[C@H]1C[C@@H]2[C@H](c3ccnc4c3cccc4)O': 39731.89917, 'c1[nH]c2c(n1)c(=O)[nH]c(=O)[nH]2': 26111.90483, 'C(C(CO)CO)O': 60609.38117, 'CC(C)(CO)CO': 64968.11402, 'CC(C)(CCO)O': 57565.50571}

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=1)`.
  rank_zero_warn(
/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
INFO:pytorch_lightning.callbacks.model_summary:
  | Name  | Type | Params
-------------------------------
0 | model | GP   | 3     
-------------------------------
3         Trainable

Training: 0it [00:00, ?it/s]

tensor([100]) best idxes
ADDITIVE CC(CCCO)O


/home/rankovic/miniconda3/envs/additive_bo/lib/python3.8/site-packages/botorch/models/utils/assorted.py:173: InputDataWarning: Input data is not contained to the unit cube. Please consider min-max scaling the input data.
  warnings.warn(msg, InputDataWarning)


Validation: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=1` reached.



Observation: CC(CCCO)O
Thought:Do I need to use a tool? No
AI: Based on the results of the initial experiments, it seems like the fourth experiment had the lowest output value, so it may be worth exploring that direction further. However, it's important to keep in mind that there may be other factors to consider when optimizing the additives for this chemical reaction. As for the next step, the proposed experiment was CC(CCCO)O. What do you think?

> Finished chain.


"Based on the results of the initial experiments, it seems like the fourth experiment had the lowest output value, so it may be worth exploring that direction further. However, it's important to keep in mind that there may be other factors to consider when optimizing the additives for this chemical reaction. As for the next step, the proposed experiment was CC(CCCO)O. What do you think?"

In [ ]:
carlos_the_frustrated_chemist = BOAgent(
    BOTools().botools,
    model="gpt-3.5-turbo"
)

prompt = (
    "Hello gpt. I want to optimize the additives for a chemical reaction. "
    "Can you please suggest what experiments to do first, "
    "and then let's do multiple optimization steps until I am satisfied."
    "Let's start with 4 experiments."
    
    "Everytime you propose an experiment, ask for my input to know the result of the experiment."
)

carlos_the_frustrated_chemist.run(prompt)

ValueError: A single string input was passed in, but this chain expects multiple inputs ({'input', 'chat_history'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`